output_directory: /app/data/Brown-TBI2AD

download:
  user: cfmmdemo
  keycloak_server: https://keycloak.cfmm.uwo.ca
  keycloak_client: dcm4chee-arc-rs
  keycloak_realm: cfmm
  dicom_url: https://dicom.cfmm.uwo.ca/dcm4chee-arc/aets/CFMMARC/rs
  study_filters:
    StudyDescription: Brown^TBI2AD
    StudyDate: 20230301-20230401
    PatientName: App*
  spectroscopy_filters:
    Modality: OT
    SeriesDescription: MRS*
  structural_filters:
    Modality: MR
    SeriesDescription: T2_*

preprocess:
  convert_to_nifti: True
  rename:
    11: sup
    10: uns

process:
  conversion:
    baseline_correction: yes
    post_processing: quecc
    quality_points: 200
    save_plot: conversion.png
  water_removal:
    hsvd_points: 512
    hsvd_ratio: 1.25
    hsvd_components: 35
    frequency_range_xmin: -1.5
    frequency_range_xmax: 0.5
    save_plot: water_removal.png
