user: cfmmdemo
output_directory: /app/data/Brown-TBI2AD
keycloak_server: https://keycloak.cfmm.uwo.ca
keycloak_client: dcm4chee-arc-rs
keycloak_realm: cfmm
dicom_url: https://dicom.cfmm.uwo.ca/dcm4chee-arc/aets/CFMMARC/rs

study_filters:
  StudyDescription: Brown^TBI2AD
  StudyDate: 20230301-20230401
  PatientName: App*
spectroscopy_filters:
  Modality: OT
  SeriesDescription: MRS*
structural_filters:
  Modality: MR
  SeriesDescription: T2_*

preprocess:
  convert_to_nifti: True
  rename:
    11: sup
    10: uns
